/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddGroupPopup: typeof import('./src/components/AddGroupPopup.vue')['default']
    AmendmentEditor: typeof import('./src/components/amendments/AmendmentEditor.vue')['default']
    AmendmentItem: typeof import('./src/components/AmendmentItem.vue')['default']
    AmendmentsView: typeof import('./src/components/amendmentsView.vue')['default']
    ApprovedAmendmentItem: typeof import('./src/components/amendments/ApprovedAmendmentItem.vue')['default']
    Ckeditor: typeof import('./src/components/ckeditor.vue')['default']
    CurrentClauseSidebar: typeof import('./src/components/amendments/CurrentClauseSidebar.vue')['default']
    Display: typeof import('./src/components/display.vue')['default']
    Document_viewer: typeof import('./src/components/document_viewer.vue')['default']
    GlassAlert: typeof import('./src/components/ui/GlassAlert.vue')['default']
    GlassButton: typeof import('./src/components/ui/GlassButton.vue')['default']
    GlassCheckbox: typeof import('./src/components/ui/GlassCheckbox.vue')['default']
    GlassCollapse: typeof import('./src/components/ui/GlassCollapse.vue')['default']
    GlassCollapseItem: typeof import('./src/components/ui/GlassCollapseItem.vue')['default']
    GlassDialog: typeof import('./src/components/ui/GlassDialog.vue')['default']
    GlassDrawer: typeof import('./src/components/ui/GlassDrawer.vue')['default']
    GlassEmpty: typeof import('./src/components/ui/GlassEmpty.vue')['default']
    GlassForm: typeof import('./src/components/ui/GlassForm.vue')['default']
    GlassFormItem: typeof import('./src/components/ui/GlassFormItem.vue')['default']
    GlassIcon: typeof import('./src/components/ui/GlassIcon.vue')['default']
    GlassInput: typeof import('./src/components/ui/GlassInput.vue')['default']
    GlassMenu: typeof import('./src/components/ui/GlassMenu.vue')['default']
    GlassMenuItem: typeof import('./src/components/ui/GlassMenuItem.vue')['default']
    GlassOption: typeof import('./src/components/ui/GlassOption.vue')['default']
    GlassSelect: typeof import('./src/components/ui/GlassSelect.vue')['default']
    GlassSkeleton: typeof import('./src/components/ui/GlassSkeleton.vue')['default']
    GlassSubMenu: typeof import('./src/components/ui/GlassSubMenu.vue')['default']
    GlassTable: typeof import('./src/components/ui/GlassTable.vue')['default']
    GlassTableColumn: typeof import('./src/components/ui/GlassTableColumn.vue')['default']
    GlassTag: typeof import('./src/components/ui/GlassTag.vue')['default']
    GlassUpload: typeof import('./src/components/ui/GlassUpload.vue')['default']
    GossipPortal: typeof import('./src/components/GossipPortal.vue')['default']
    GreenCKEditor: typeof import('./src/components/GreenCKEditor.vue')['default']
    GreenCKEditorExample: typeof import('./src/components/GreenCKEditorExample.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
